#!/usr/bin/env python3
"""
GitHub Profile Analyzer - Report Export
분석 결과를 다양한 형식으로 내보내기
"""

import json
import argparse
import sys
from datetime import datetime
from typing import Dict, Any


def export_to_markdown(data: Dict[str, Any], output_file: str):
    """Markdown 형식으로 내보내기"""
    username = data.get('username', 'Unknown')
    repos = data.get('repositories', [])
    stats = data.get('statistics', {})
    
    md_content = f"""# GitHub Profile Analysis Report

**사용자**: {username}  
**생성일**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 📊 종합 통계

| 항목 | 값 |
|------|-----|
| 총 리포지토리 수 | {stats.get('total_repositories', 0)} |
| 총 커밋 수 | {stats.get('total_commits', 0):,} |
| 총 스타 수 | {stats.get('total_stars', 0):,} |
| 총 포크 수 | {stats.get('total_forks', 0):,} |
| 총 코드량 | {stats.get('total_size_mb', 0):.2f} MB |
| 평균 커밋/리포 | {stats.get('avg_commits_per_repo', 0):.2f} |
| 평균 스타/리포 | {stats.get('avg_stars_per_repo', 0):.2f} |

---

## 💻 언어별 분포

| 언어 | 비율 | 크기 |
|------|------|------|
"""
    
    # 언어 분포
    lang_dist = stats.get('language_distribution', {})
    total_bytes = sum(lang_dist.values())
    
    sorted_langs = sorted(lang_dist.items(), key=lambda x: x[1], reverse=True)[:10]
    for lang, bytes_count in sorted_langs:
        percentage = (bytes_count / total_bytes * 100) if total_bytes > 0 else 0
        mb_size = bytes_count / (1024 * 1024)
        md_content += f"| {lang} | {percentage:.2f}% | {mb_size:.2f} MB |\n"
    
    # 리포지토리 목록
    md_content += "\n---\n\n## 📦 리포지토리 목록\n\n"
    
    sorted_repos = sorted(repos, key=lambda x: x.get('commit_count', 0), reverse=True)
    
    for i, repo in enumerate(sorted_repos[:20], 1):
        md_content += f"""
### {i}. [{repo['name']}]({repo['url']})

**설명**: {repo.get('description', 'No description')}

- **커밋**: {repo.get('commit_count', 0):,}
- **스타**: {repo.get('stars', 0):,}
- **포크**: {repo.get('forks', 0):,}
- **생성일**: {repo.get('created_at', 'N/A')}
- **업데이트**: {repo.get('updated_at', 'N/A')}

"""
        
        # 언어 정보
        if repo.get('languages'):
            langs = ', '.join([f"{k}" for k in list(repo['languages'].keys())[:5]])
            md_content += f"**사용 언어**: {langs}\n\n"
    
    md_content += "\n---\n\n*Generated by GitHub Profile Analyzer*\n"
    
    # 파일 저장
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(md_content)
        print(f"✅ Markdown 리포트 생성: {output_file}")
    except Exception as e:
        print(f"❌ Markdown 저장 오류: {e}")


def export_to_csv(data: Dict[str, Any], output_file: str):
    """CSV 형식으로 내보내기 (리포지토리 목록)"""
    import csv
    
    repos = data.get('repositories', [])
    
    try:
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            fieldnames = ['name', 'url', 'description', 'stars', 'forks', 
                         'commit_count', 'size', 'created_at', 'updated_at']
            
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            
            for repo in repos:
                writer.writerow({
                    'name': repo.get('name', ''),
                    'url': repo.get('url', ''),
                    'description': repo.get('description', ''),
                    'stars': repo.get('stars', 0),
                    'forks': repo.get('forks', 0),
                    'commit_count': repo.get('commit_count', 0),
                    'size': repo.get('size', 0),
                    'created_at': repo.get('created_at', ''),
                    'updated_at': repo.get('updated_at', '')
                })
        
        print(f"✅ CSV 파일 생성: {output_file}")
        
    except Exception as e:
        print(f"❌ CSV 저장 오류: {e}")


def export_to_html(data: Dict[str, Any], output_file: str):
    """HTML 형식으로 내보내기"""
    username = data.get('username', 'Unknown')
    repos = data.get('repositories', [])
    stats = data.get('statistics', {})
    
    html_content = f"""<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitHub Profile Analysis - {username}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        .stat-card {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .stat-card h3 {{
            margin: 0 0 10px 0;
            color: #667eea;
            font-size: 14px;
        }}
        .stat-card .value {{
            font-size: 28px;
            font-weight: bold;
            color: #333;
        }}
        .section {{
            background: white;
            padding: 25px;
            border-radius: 8px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .repo-card {{
            border-left: 4px solid #667eea;
            padding: 15px;
            margin: 15px 0;
            background: #f9f9f9;
        }}
        .repo-card h3 {{
            margin: 0 0 10px 0;
        }}
        .repo-card a {{
            color: #667eea;
            text-decoration: none;
        }}
        .repo-card a:hover {{
            text-decoration: underline;
        }}
        .badge {{
            display: inline-block;
            padding: 4px 8px;
            margin: 2px;
            border-radius: 3px;
            font-size: 12px;
            background: #e0e7ff;
            color: #4c51bf;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background-color: #667eea;
            color: white;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 GitHub Profile Analysis</h1>
        <h2>{username}</h2>
        <p>생성일: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <h3>리포지토리</h3>
            <div class="value">{stats.get('total_repositories', 0)}</div>
        </div>
        <div class="stat-card">
            <h3>총 커밋</h3>
            <div class="value">{stats.get('total_commits', 0):,}</div>
        </div>
        <div class="stat-card">
            <h3>총 스타</h3>
            <div class="value">{stats.get('total_stars', 0):,}</div>
        </div>
        <div class="stat-card">
            <h3>코드량</h3>
            <div class="value">{stats.get('total_size_mb', 0):.1f} MB</div>
        </div>
    </div>

    <div class="section">
        <h2>💻 언어별 분포</h2>
        <table>
            <thead>
                <tr>
                    <th>언어</th>
                    <th>비율</th>
                    <th>크기</th>
                </tr>
            </thead>
            <tbody>
"""
    
    # 언어 분포
    lang_dist = stats.get('language_distribution', {})
    total_bytes = sum(lang_dist.values())
    
    sorted_langs = sorted(lang_dist.items(), key=lambda x: x[1], reverse=True)[:10]
    for lang, bytes_count in sorted_langs:
        percentage = (bytes_count / total_bytes * 100) if total_bytes > 0 else 0
        mb_size = bytes_count / (1024 * 1024)
        html_content += f"""
                <tr>
                    <td><strong>{lang}</strong></td>
                    <td>{percentage:.2f}%</td>
                    <td>{mb_size:.2f} MB</td>
                </tr>
"""
    
    html_content += """
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>📦 리포지토리 목록</h2>
"""
    
    # 리포지토리 목록
    sorted_repos = sorted(repos, key=lambda x: x.get('commit_count', 0), reverse=True)
    
    for i, repo in enumerate(sorted_repos[:20], 1):
        langs = ', '.join(list(repo.get('languages', {}).keys())[:5])
        
        html_content += f"""
        <div class="repo-card">
            <h3>{i}. <a href="{repo['url']}" target="_blank">{repo['name']}</a></h3>
            <p>{repo.get('description', 'No description')}</p>
            <div>
                <span class="badge">⭐ {repo.get('stars', 0):,} stars</span>
                <span class="badge">🔀 {repo.get('forks', 0):,} forks</span>
                <span class="badge">📝 {repo.get('commit_count', 0):,} commits</span>
            </div>
            <p><small>생성: {repo.get('created_at', 'N/A')} | 업데이트: {repo.get('updated_at', 'N/A')}</small></p>
            {f'<p><strong>언어:</strong> {langs}</p>' if langs else ''}
        </div>
"""
    
    html_content += """
    </div>

    <footer style="text-align: center; margin-top: 40px; color: #666;">
        <p>Generated by GitHub Profile Analyzer</p>
    </footer>
</body>
</html>
"""
    
    # 파일 저장
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"✅ HTML 리포트 생성: {output_file}")
    except Exception as e:
        print(f"❌ HTML 저장 오류: {e}")


def main():
    """메인 함수"""
    parser = argparse.ArgumentParser(
        description='GitHub Profile Analyzer - Report Export',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
예제:
  %(prog)s result.json --markdown report.md
  %(prog)s result.json --csv repos.csv
  %(prog)s result.json --html report.html
  %(prog)s result.json --all output_prefix
        """
    )
    
    parser.add_argument(
        'json_file',
        type=str,
        help='분석 결과 JSON 파일'
    )
    
    parser.add_argument(
        '--markdown', '-md',
        type=str,
        help='Markdown 파일로 내보내기'
    )
    
    parser.add_argument(
        '--csv',
        type=str,
        help='CSV 파일로 내보내기'
    )
    
    parser.add_argument(
        '--html',
        type=str,
        help='HTML 파일로 내보내기'
    )
    
    parser.add_argument(
        '--all',
        type=str,
        help='모든 형식으로 내보내기 (접두어 지정)'
    )
    
    args = parser.parse_args()
    
    # JSON 파일 로드
    try:
        with open(args.json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"✅ 파일 로드: {args.json_file}\n")
    except Exception as e:
        print(f"❌ 파일 로드 오류: {e}")
        return 1
    
    username = data.get('username', 'unknown')
    
    # 내보내기 실행
    if args.all:
        prefix = args.all
        export_to_markdown(data, f"{prefix}_{username}_report.md")
        export_to_csv(data, f"{prefix}_{username}_repos.csv")
        export_to_html(data, f"{prefix}_{username}_report.html")
    else:
        if args.markdown:
            export_to_markdown(data, args.markdown)
        
        if args.csv:
            export_to_csv(data, args.csv)
        
        if args.html:
            export_to_html(data, args.html)
        
        if not (args.markdown or args.csv or args.html):
            print("❌ 내보낼 형식을 지정하세요 (--markdown, --csv, --html, 또는 --all)")
            return 1
    
    print("\n✅ 내보내기 완료!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
